### ISSUE TITLE
How to verfiy if the beamforming node is interfaced with proper mic? and Is it possible to get the raw audio file of individual channel?

### ISSUE THREAD

**Issue by ajaygunalan** [balkce/beamform#1]
Hey,

I would like to use this package for [XMOS 7 array Microphone](https://www.xmos.com/products/voice/micarray). But, when I launched `das.launch`, I got some error, so I did `jack_control start` (to start jack server) and `usermod -a -G audio <theusername>` (to avoid cannot allocate memory: permission denied)

Now, I get:
```
... logging to /home/ajay/.ros/log/1332ee66-4f2f-11ea-990f-708bcda03968/roslaunch-ajay-5744.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ajay:38401/

SUMMARY
========

PARAMETERS
 * /beamform/angle_interf10: 181.0
 * /beamform/angle_interf11: 181.0
 * /beamform/angle_interf12: 181.0
 * /beamform/angle_interf13: 181.0
 * /beamform/angle_interf14: 181.0
 * /beamform/angle_interf15: 181.0
 * /beamform/angle_interf1: 90.0
 * /beamform/angle_interf2: 181.0
 * /beamform/angle_interf3: 181.0
 * /beamform/angle_interf4: 181.0
 * /beamform/angle_interf5: 181.0
 * /beamform/angle_interf6: 181.0
 * /beamform/angle_interf7: 181.0
 * /beamform/angle_interf8: 181.0
 * /beamform/angle_interf9: 181.0
 * /beamform/auto_connect: True
 * /beamform/initial_angle: 0.0
 * /beamform/mic0/id: 0
 * /beamform/mic0/x: 0.0
 * /beamform/mic0/y: 0.0
 * /beamform/mic0/z: 0.0
 * /beamform/mic1/id: 1
 * /beamform/mic1/x: -0.0225
 * /beamform/mic1/y: 0.03897
 * /beamform/mic1/z: 0.0
 * /beamform/mic2/id: 2
 * /beamform/mic2/x: -0.045
 * /beamform/mic2/y: 0.0
 * /beamform/mic2/z: 0.0
 * /beamform/mic3/id: 3
 * /beamform/mic3/x: -0.0225
 * /beamform/mic3/y: -0.03897
 * /beamform/mic3/z: 0.0
 * /beamform/mic4/id: 4
 * /beamform/mic4/x: 0.0225
 * /beamform/mic4/y: -0.03897
 * /beamform/mic4/z: 0.0
 * /beamform/mic5/id: 5
 * /beamform/mic5/x: 0.045
 * /beamform/mic5/y: 0.0
 * /beamform/mic5/z: 0.0
 * /beamform/mic6/id: 6
 * /beamform/mic6/x: 0.0225
 * /beamform/mic6/y: 0.03897
 * /beamform/mic6/z: 0.0
 * /beamform/output_type: 0
 * /beamform/ros_output_sample_rate: 48000
 * /beamform/verbose: True
 * /beamform/write_file: True
 * /beamform/write_file_path: 
 * /beamform/write_xrun: False
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /
    beamform (beamform/das)

auto-starting new master
process[master]: started with pid [5754]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 1332ee66-4f2f-11ea-990f-708bcda03968
process[rosout-1]: started with pid [5765]
started core service [/rosout]
process[beamform-2]: started with pid [5772]
ROS Node name: /beamform
Beamform ROS parameters: 
[ INFO] [1581687419.939918129]: Verbose: 1
[ INFO] [1581687419.940771589]: Initial angle: 0.000000
[ INFO] [1581687419.941067242]: Mic 0: (0.000000,0.000000) (0.000000,0.000000)
[ INFO] [1581687419.941415528]: Mic 1: (-0.022500,0.038970) (0.044999,120.000728)
[ INFO] [1581687419.941708336]: Mic 2: (-0.045000,0.000000) (0.045000,180.000000)
[ INFO] [1581687419.942016271]: Mic 3: (-0.022500,-0.038970) (0.044999,-120.000728)
[ INFO] [1581687419.942293886]: Mic 4: (0.022500,-0.038970) (0.044999,-59.999272)
[ INFO] [1581687419.942667764]: Mic 5: (0.045000,0.000000) (0.045000,0.000000)
[ INFO] [1581687419.942910259]: Mic 6: (0.022500,0.038970) (0.044999,59.999272)
[ INFO] [1581687419.943291710]: Interference 1 at: 90.000000
[ INFO] [1581687419.943517512]: Number of microphones: 7
Coordinates of microphones, relative to Mic0: 
Mic #0
	 x: 0
	 y: 0
	 d: 0
	 a: 0
Mic #1
	 x: -0.0225
	 y: 0.03897
	 d: 0.044999
	 a: 120.001
Mic #2
	 x: -0.045
	 y: 0
	 d: 0.045
	 a: 180
Mic #3
	 x: -0.0225
	 y: -0.03897
	 d: 0.044999
	 a: -120.001
Mic #4
	 x: 0.0225
	 y: -0.03897
	 d: 0.044999
	 a: -59.9993
Mic #5
	 x: 0.045
	 y: 0
	 d: 0.045
	 a: 0
Mic #6
	 x: 0.0225
	 y: 0.03897
	 d: 0.044999
	 a: 59.9993

JACK ROS parameters: /beamform
[ INFO] [1581687419.945915432]: Output type: ROSJACK_OUT_BOTH
[ INFO] [1581687419.946164005]: Auto connect: 1
[ INFO] [1581687419.946401290]: Write output to audio file: 1
[ WARN] [1581687419.946630759]: Audio file path argument found in ROS param server is empty, using default value (/home/ajay/rosjack_write_file.wav).
[ INFO] [1581687419.946855756]: Write XRUN count to file: 0
[ INFO] [1581687419.947067210]: ROS Output Sample Rate: 48000
Connecting to Jack Server...
JACK window size: 1024
JACK sample rate: 48000
ROS Output Sample Rate and JACK sample rate are the same. Not creating sample rate converter.
Writing ROS output in: /home/ajay/rosjack_write_file.wav
Audio file info:
	Sample Rate: 48000
	Channels: 1
	Format: WAV, PCM 16-bit
Agent activated.
jack_connect called with a NULL port name
Connecting input ports... Cannot connect input port beamform:input_3.
[ WARN] [1581687419.983749097]: Not connecting any more input ports, sticking with the ones that were connected.

done.
Pre-allocating space for internal buffers.
Overlap Info:
	 Start index of first window: 2560
	 Start index of last window : 512
New delays:
	 0 -> 0.000000
	 1 -> 0.000066
	 2 -> 0.000131
	 3 -> 0.000066
	 4 -> -0.000066
	 5 -> -0.000131
	 6 -> -0.000066
[ INFO] [1581687420.234596693]: Beamform ROS node started.

```

I wonder is there any tutorial for this package? Because, I'm not sure on how to interface with the **proper mic** and to verify if its working.**The beamform node seems to run even when i disconnect the mic.** I think, it has not selected the appropriate mic. How to do it ? and  what does `auto_connect: false` do? and what does `d` and `a` means in Mic #0, Mic #1, etc.. ? 

Finally, **Is there anyway to get the raw audio data from each of the channels separately?**

Other additional info:

`cat /proc/asound/cards`
```
 0 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xf7230000 irq 37
 1 [NVidia         ]: HDA-Intel - HDA NVidia
                      HDA NVidia at 0xf7080000 irq 17
 2 [UAC20          ]: USB-Audio - XMOS Microphone Array UAC2.0
                      XMOS XMOS Microphone Array UAC2.0 at usb-0000:00:14.0-5, full speed
```
` arecord -l`
```
**** List of CAPTURE Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC1150 Analog [ALC1150 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 2: ALC1150 Alt Analog [ALC1150 Alt Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: UAC20 [XMOS Microphone Array UAC2.0], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by balkce** [comment]
First off: I've had issues running a JACK server through the jack_control script (https://www.linuxquestions.org/questions/linux-newbie-8/using-jack2-dbus-jack_control-start-gives-error-dbus-exception-org-jackaudio-error-4175501811/) I recommend to run it by either directly running the jackd command or through the QJackCtl GUI. The error you see states that the JACK side of the program was not able to connect the third microphone. This is probably because JACK is interfacing with your internal audio card instead of the XMOS array. 

Second, there's no tutorial for this package as of yet, but to know which microphone is interfaced with each input, you can use the information in beamform_config.yaml to establish which JACK agent input is for what microphone in terms of their coordinates. Another way is through manually connecting your inputs through the functionalities that JACK server provides, of hotswapping your inputs. 

The beamform ROS node will run independently if you physically disconnect your mic, however the JACK side of the program will not.

The auto_connect parameter is there in case you don't want the JACK agent to automatically connect it's inputs to the JACK server outputs. In your case, once you have the JACK server properly configured to interface with the XMOS array, this parameter should be set to true. 

d and a are the polar coordinates of each microphone, converted from the Cartesian coordinates set in beamform_config.yaml

Because of the nature of beamforming, only the audio data coming from the direction of interest is separated from the rest and, thus, only one output channel is given. As you can see in the log, this information is written in the WAV file located in /home/ajay/rosjack_write_file.wav as well as reporting it in the jack_audio ROS topic and through its JACK output. As for the input channels, the program does not store it anywhere, however you could use JACK to manually connect a microphone to a speaker to monitor which microphone is which. 

Hope this clears up some of your questions.

**Comment by ajaygunalan** [comment]
Hey,

Thank you very much for your immediate and elaborated response. It helped me a lot. So now, I run through `qjackctl` and the mic is configured by `setup->interface` and other setting are as follows:
![jack_configuration](https://user-images.githubusercontent.com/27948283/74729178-51b08c80-5244-11ea-9cdc-6f2f04ec791b.png)
I tried with different launch files and the output so far is not satisfactory.  I tired varying my sound source with various angles around mic array at distance of 80 cm. (In some trials, less than 80 cm). But, the issue is I'm able to hear sound from all direction or else too much of noise in some cases.
Is my sound source too close? and do you suggest any particular experimental setup (sound source: distance, azimuth, latency, reverberation  free  environments, etc...) to get a benchmark result?

**Comment by balkce** [comment]
It's important to remember that most of the beamformers implemented in this package are pretty basic (DAS, for example), which may not provide such a good interference reduction. I made this to have a basis of comparison with other more sophisticated methods.

However, I would suggest to test the "gss" beamformer which is re-creation of the work in:

J. Valin, S. Yamamoto, J. Rouat, F. Michaud, K. Nakadai and H. G. Okuno, "Robust Recognition of Simultaneous Speech by a Mobile Robot," in IEEE Transactions on Robotics, vol. 23, no. 4, pp. 742-752, 2007.

Of all the ones implemented in this package, this probably has the most chance of providing good results.

For the time being, I'm closing this thread, since it appears the original issues have been resolved. If you have any more questions or other issues, I'd suggest to open another thread.
